/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlycafe;

/**
 *
 * @author ThanhNam
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuDangNhap = new javax.swing.JMenu();
        mniDangNhap = new javax.swing.JMenuItem();
        mniExit = new javax.swing.JMenuItem();
        mnuOrder = new javax.swing.JMenu();
        mnitGioHang = new javax.swing.JMenuItem();
        mitHoaDon = new javax.swing.JMenuItem();
        mnuNhanVien = new javax.swing.JMenu();
        mnuDoanhThu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ QUẦY BAR CAFÉ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(920, 720));

        Desktop.setPreferredSize(new java.awt.Dimension(920, 720));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        mnuDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N
        mnuDangNhap.setText("Đăng Nhập");

        mniDangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User group.png"))); // NOI18N
        mniDangNhap.setText("Đăng Nhập");
        mniDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangNhapActionPerformed(evt);
            }
        });
        mnuDangNhap.add(mniDangNhap);

        mniExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mniExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Log out.png"))); // NOI18N
        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuDangNhap.add(mniExit);

        jMenuBar1.add(mnuDangNhap);

        mnuOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Basket.png"))); // NOI18N
        mnuOrder.setText("Order");

        mnitGioHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Basket.png"))); // NOI18N
        mnitGioHang.setText("Giỏ Hàng");
        mnitGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitGioHangActionPerformed(evt);
            }
        });
        mnuOrder.add(mnitGioHang);

        mitHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/List.png"))); // NOI18N
        mitHoaDon.setText("Hóa Đơn");
        mitHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitHoaDonActionPerformed(evt);
            }
        });
        mnuOrder.add(mitHoaDon);

        jMenuBar1.add(mnuOrder);

        mnuNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User group.png"))); // NOI18N
        mnuNhanVien.setText("Nhân Viên");
        mnuNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuNhanVienMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuNhanVien);

        mnuDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Diagram.png"))); // NOI18N
        mnuDoanhThu.setText("Doanh Thu");
        mnuDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuDoanhThuMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuDoanhThu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangNhapActionPerformed
        // TODO add your handling code here:
        frmDangNhap frm = new frmDangNhap();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_mniDangNhapActionPerformed

    private void mnitGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitGioHangActionPerformed
        // TODO add your handling code here:
        frmOrder frm = new frmOrder();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_mnitGioHangActionPerformed

    private void mitHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitHoaDonActionPerformed
        // TODO add your handling code here:
        frmHoaDon frm = new frmHoaDon();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_mitHoaDonActionPerformed

    private void mnuNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuNhanVienMouseClicked
        // TODO add your handling code here:
        frmDSNV frm = new frmDSNV();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuNhanVienMouseClicked

    private void mnuDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuDoanhThuMouseClicked
        // TODO add your handling code here:
        frmChiTietHoaDon frm = new frmChiTietHoaDon();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_mnuDoanhThuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mitHoaDon;
    private javax.swing.JMenuItem mniDangNhap;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mnitGioHang;
    private javax.swing.JMenu mnuDangNhap;
    private javax.swing.JMenu mnuDoanhThu;
    private javax.swing.JMenu mnuNhanVien;
    private javax.swing.JMenu mnuOrder;
    // End of variables declaration//GEN-END:variables
}
