/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrame;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haiiinvv
 */
public class SanPham extends javax.swing.JFrame {

    List<classSanpham> listnv = new ArrayList<>();
    int vitri;
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form SanPham
     */
    public SanPham() {
        initComponents();
        model = (DefaultTableModel) tablesp.getModel();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnImage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbten = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDangxuat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSanPham = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLoaiSanPham3 = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtGiaTien = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablesp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SẢN PHẨM");

        pnImage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnImageLayout = new javax.swing.GroupLayout(pnImage);
        pnImage.setLayout(pnImageLayout);
        pnImageLayout.setHorizontalGroup(
            pnImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );
        pnImageLayout.setVerticalGroup(
            pnImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        jLabel2.setText("Mã Sản Phẩm");

        lbten.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbten.setText("Tên Nhân Viên: ...");

        jLabel3.setText("Sản Phẩm");

        btnDangxuat.setText("Đăng xuất");
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });

        jLabel4.setText("Loại Sản Phẩm");

        jLabel5.setText("Giá Tiền");

        txtLoaiSanPham3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoaiSanPham3ActionPerformed(evt);
            }
        });

        txtGiaTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTienActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tablesp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Loại Sản Phẩm", "Giá Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablesp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablespMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablesp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLoaiSanPham3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(pnImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbten)
                .addGap(18, 18, 18)
                .addComponent(btnDangxuat)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbten)
                    .addComponent(btnDangxuat))
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtLoaiSanPham3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoaiSanPham3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoaiSanPham3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoaiSanPham3ActionPerformed

    private void txtGiaTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTienActionPerformed

    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnDangxuatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        addlist();
        addtb();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
        addtb();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tablespMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablespMouseClicked
        int row = tablesp.getSelectedRow();
        if (row >= 0) {
            vitri = row;
            display(vitri);
        }
    }//GEN-LAST:event_tablespMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int v = tablesp.getSelectedRow();
        listnv.remove(vitri);
        addtb();
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPham().setVisible(true);
            }
        });
    }

    public boolean check(String a) {
        boolean chk = false;
        for (int i = 0; i < listnv.size(); i++) {
            if (listnv.get(i).getMaSP().equals(txtID.getText())) {
                chk = true;
            }
        }
        return chk;
    }

    public void addlist() {

        classSanpham nv = new classSanpham();
        try {
            if (check(txtID.getText()) == true) {
                JOptionPane.showMessageDialog(this, "ID da ton tai");
                return;
            } else {
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        try {
            if (txtID.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống");
                txtID.requestFocus();
                return;
            } else {
                nv.setMaSP(txtID.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi ");
            return;
        }
        try {
            if (txtSanPham.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống");
                return;
            } else {
                nv.setSanPham(txtSanPham.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi ");
            return;
        }
        try {
            if (txtLoaiSanPham3.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống");
                return;
            } else {
                nv.setLoai(txtLoaiSanPham3.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi ");
            return;
        }
        try {
            if (txtGiaTien.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống");
                return;
            } else {
                nv.setSotien(Integer.parseInt(txtGiaTien.getText()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Phai nhap so ");
            return;
        }

        listnv.add(nv);

    }

    public void addtb() {
        model.setRowCount(0);
        for (classSanpham n : listnv) {
            model.addRow(new Object[]{n.getMaSP(), n.getSanPham(), n.getLoai(), n.getSotien() + " VNĐ"});
        }
    }

    public void display(int vitri) {
        if (vitri >= 0) {
            classSanpham v = listnv.get(vitri);
            txtID.setText(v.getMaSP());
            txtSanPham.setText(v.getSanPham());
            txtLoaiSanPham3.setText(v.getLoai());
            txtGiaTien.setText(String.valueOf(v.getSotien()));

            tablesp.setRowSelectionInterval(vitri, vitri);

        } else {

        }
    }

    public void update() {
        int index = tablesp.getSelectedRow();
        classSanpham s = listnv.get(vitri);

        try {
            if (check(txtID.getText()) == true) {
                JOptionPane.showMessageDialog(this, "ID da ton tai");
                return;
            } else {
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        try {
            if (txtID.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống");
                txtID.requestFocus();
                return;
            } else {
                s.MaSP = txtID.getText();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi ");
            return;
        }
        try {
            if (txtSanPham.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống");
                return;
            } else {
                s.SanPham = txtSanPham.getText();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi ");
            return;
        }
        try {
            if (txtLoaiSanPham3.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống");
                return;
            } else {
                s.Loai = txtLoaiSanPham3.getText();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi ");
            return;
        }

        try {
            if (txtGiaTien.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Không được bỏ trống");
                return;
            } else {
                s.Sotien = Integer.parseInt(txtGiaTien.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Phai nhap so ");
            return;
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangxuat;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbten;
    private javax.swing.JPanel pnImage;
    private javax.swing.JTable tablesp;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLoaiSanPham3;
    private javax.swing.JTextField txtSanPham;
    // End of variables declaration//GEN-END:variables

}
